import torch

from mlkem_gpu.cbd_gpu import poly_cbd_eta1, poly_cbd_eta2
from mlkem_gpu.device import DEVICE
from mlkem_gpu.params import KYBER_N


NUM_POLYNOMIALS = 10


def test_cbd_eta1_coefficients_are_in_valid_range():
    """
    ETA1 = 3 for ML-KEM-512.

    Therefore every coefficient generated by poly_cbd_eta1()
    must lie in the range [-3, 3].
    """
    for _ in range(NUM_POLYNOMIALS):
        buf = torch.randint(
            low=0,
            high=256,
            size=(192,),
            dtype=torch.uint8,
            device=DEVICE,
        )

        poly = poly_cbd_eta1(buf)

        assert poly.coeffs.shape == (KYBER_N,)
        assert torch.all(poly.coeffs >= -3)
        assert torch.all(poly.coeffs <= 3)


def test_cbd_eta2_coefficients_are_in_valid_range():
    """
    ETA2 = 2 for ML-KEM-512.

    Therefore every coefficient generated by poly_cbd_eta2()
    must lie in the range [-2, 2].
    """
    for _ in range(NUM_POLYNOMIALS):
        buf = torch.randint(
            low=0,
            high=256,
            size=(128,),
            dtype=torch.uint8,
            device=DEVICE,
        )

        poly = poly_cbd_eta2(buf)

        assert poly.coeffs.shape == (KYBER_N,)
        assert torch.all(poly.coeffs >= -2)
        assert torch.all(poly.coeffs <= 2)